# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1haJSKAUD-m8y4_Hv1xR2wGyrqyZlv0dz
"""

from textblob import TextBlob

def analyze_sentiment(text):
    # Create a TextBlob object
    blob = TextBlob(text)

    # Perform sentiment analysis
    sentiment_score = blob.sentiment.polarity

    # Determine sentiment label
    if sentiment_score > 0:
        sentiment_label = "Positive"
    elif sentiment_score < 0:
        sentiment_label = "Negative"
    else:
        sentiment_label = "Neutral"

    return sentiment_label, sentiment_score

def main():
    # Example text
    text = "I love this product! It's amazing."

    # Analyze sentiment
    sentiment_label, sentiment_score = analyze_sentiment(text)

    # Print results
    print("Text:", text)
    print("Sentiment:", sentiment_label)
    print("Sentiment Score:", sentiment_score)

if __name__ == "__main__":
    main()